### ISSUE TITLE
cant store new presets in the librarian

### ISSUE THREAD

**Issue by hugowester** [ElliotGarbus/Enzo-Editor-and-Librarian#1]
Hi...i used the editor some months ago,i think i was still in high sierra...i edited presets and saved them with new names in a brezze...
now in mojave it is impossible to store changes,and it is impossible to rename them.i´m using a disaster area box...thanks for the editor...dont know what is wrong

**Comment by ElliotGarbus** [comment]
What DisasterArea Device are you using?  You can NOT use a DisasterArea MIDI box.  The editor requires a bi-directional midi connection.  There are a number of DA devices that do provide a bi-directional connection, including the qConnect.
