### ISSUE TITLE
Trying to save/update preset X says "preset is in library as X"

### ISSUE THREAD

**Issue by roaet** [ElliotGarbus/Enzo-Editor-and-Librarian#11]
It does not provide me with a dialog to rename or make a new one. Update preset and the Save make the same error.

![image](https://user-images.githubusercontent.com/312320/172957390-6e237e84-63d3-491b-b601-0d508fe122f8.png)

**Comment by ElliotGarbus** [comment]
The presets in the library all must be unique.  This is a design decision I made.  The pedal does not associate a name with a preset.  I do a reverse look up, I use the content of a preset to associate the preset data with a name.  If the preset data is the same as an entry already in the library, it will not save or update.  Try changing a parameter and do a save to "Save to Enzo and Lib"

**Comment by roaet** [comment]
If I do a save to enzo and lib after changing a preset it causes the same error.

**Comment by roaet** [comment]
And holy moly you're fast. Thank you <3

**Comment by roaet** [comment]
![image](https://user-images.githubusercontent.com/312320/172960574-96029d9c-b2e3-46e7-bd35-0eddd975d285.png)

**Comment by roaet** [comment]
I modified the tap/tempo and it somehow allowed me to save. And now I can save the patches as expected. I am no longer blocked, but it was an interesting bug. Thank you!
