### ISSUE TITLE
Failed to execute script main - Unable to find any valuable Window provider (VirtualBox on Ubuntu, w/Win10 guest)

### ISSUE THREAD

**Issue by daveX99** [ElliotGarbus/Enzo-Editor-and-Librarian#12]
Hello:

I have installed the Enzo Editor and I'm getting the 'Failed to execute script main' pop up.  I am experiencing the same with the Hedra Editor as well.  I have looked through the existing issues, and have not found any solution.

I am running these programs on Windows 10, via virtualbox on an Ubuntu Linux host machine.   I am a bit ignorant of Windows, but I am pretty sure my anti-virus is turned off. For both installations I have checked for the presence of a main.ini file in the _C:\Users\your_user_name\Documents\[Enzo/Hedra] Edit Presets and Library_  directories, but there is no file, only library.json.

I am a web developer & linux admin, but not big in python or windows, but let me know what other info/help I can provide.

Thanks.

-dave.

I am attaching a log file from the last attempt at opening the Enzo Editor.

`[INFO   ] Logger: Record log in C:\Users\daves\.kivy\logs\kivy_23-03-24_9.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "C:\Program Files (x86)\Enzo Editor and Librarian\kivy\__init__.pyc"
[INFO   ] Python: v3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
[INFO   ] Python: Interpreter at "C:\Program Files (x86)\Enzo Editor and Librarian\EnzoEdit.exe"
[INFO   ] Factory: 184 symbols loaded
[DEBUG  ] Cache: register <kv.lang> with limit=None, timeout=None
[DEBUG  ] Cache: register <kv.image> with limit=None, timeout=60
[DEBUG  ] Cache: register <kv.atlas> with limit=None, timeout=None
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[DEBUG  ] Cache: register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] Cache: register <kv.shader> with limit=1000, timeout=3600
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] Window: Activate GLES2/ANGLE context
[CRITICAL] Window: Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'Could not initialize OpenGL / GLES library'
  File "site-packages\kivy\core\__init__.py", line 71, in core_select_lib
  File "site-packages\kivy\core\window\window_sdl2.py", line 152, in __init__
  File "site-packages\kivy\core\window\__init__.py", line 981, in __init__
  File "site-packages\kivy\core\window\window_sdl2.py", line 290, in create_window
  File "kivy\core\window\_window_sdl2.pyx", line 224, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy\core\window\_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

[DEBUG  ] Cache: register <textinput.label> with limit=None, timeout=60.0
[DEBUG  ] Cache: register <textinput.width> with limit=None, timeout=60.0
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "main.py", line 22, in <module>
[WARNING] stderr:   File "c:\users\ellio\kivy_venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
[WARNING] stderr:   File "MerisCommon\meris_midi.py", line 2, in <module>
[WARNING] stderr:   File "c:\users\ellio\kivy_venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
[WARNING] stderr:   File "site-packages\mido\backends\rtmidi.py", line 8, in <module>
[WARNING] stderr:   File "c:\users\ellio\kivy_venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
[WARNING] stderr:   File "site-packages\rtmidi\__init__.py", line 4, in <module>
[WARNING] stderr:     
[WARNING] stderr: ImportError: DLL load failed: The specified module could not be found.
`

**Comment by ElliotGarbus** [comment]
I have no experience using VirtualBox.  
It looks like there are 2 issues:
1) The correct version of OpenGL is not provided by the Virtual box.  Graphics driver support OpenGL 2.1 is required at the minimum. Make sure you can support at least OpenGL 2.1 in the Virtual box.
2) There is an issue with rtmidi, the library that provides midi functionality.  My guess is that there is an issue accessing the USB or other shared system resource.  Check for VM configuration options.
I wish I could be more help.  Good Luck!

**Comment by daveX99** [comment]
Thanks for your reply.  I looked into the OpenGL issue, and could not find a solution, and even tried Gnome Boxes as an alternative Vitrtualization set up (I think it uses qemu in the background...).  

What worked, finally was just setting up WINE and running the editors from there.  It's a bit clunky, but seems to work okay.  I have not tested all the functionality yet, but will open a separate thread if necessary.

Thanks for the editors and the support here.
-dave.

**Comment by ElliotGarbus** [comment]
Glad to here you have things working... (so far).  I'd expect if midi is working, all of the functionality should be there.  Please let me know if to all works under WINE.  

There is some Windows Specific code used to find specific Windows directories (Download, Document,  Desktop) and to enumerate the disk drives.  I would expect WINE can able to handle these operations.  Try using the import and export dialogs to check the file I/O.

**Comment by daveX99** [comment]
It looks like it's working fine.  I am able to save and load files.  I had an error message appear at one point about not finding or being able to write to the various (windows) drives, but the error was mine: I am pretty sure that I didn't have the pedal connected correctly at the time.

For the record, I am running Ubuntu 20.04, and have WINE 5.0 installed.

If I run into any problems, I will open a new thread here. Thanks.

**Comment by ElliotGarbus** [comment]
Glad to hear you’re up and running. Enjoy!
