### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by Meris12341234** [ElliotGarbus/Enzo-Editor-and-Librarian#7]
Hi Elliot,

I get "Failed to execute script main" when I run the Enzo editor.  Here is the log file I get.

[kivy_21-04-07_2.txt](https://github.com/ElliotGarbus/Enzo-Editor-and-Librarian/files/6275235/kivy_21-04-07_2.txt)

I know you suggest disabling antivirus during install but on my work system this is not an option.  I have tried running both the install and the program as administrator but no luck.  I am connecting from a Morningstar MC-8 and it communicates with the Enzo just fine through its TRS out. 

Any ideas?  

Cheers,

Mike

**Comment by ElliotGarbus** [comment]
I believe there are 2 issues here:
1) There is something blocking the creation of a midi port.  It is possible this is related to your virus scanner or an issue at install.  I suggest rebooting your laptop and seeing if you get a different result.  I don't have any other suggestion.  I'm concerned this may simply be a virus scanner related issue.  If you get a different result after reboot, or a different message in the log file, let me know.
2) the Omni-ports on the MC8 only send midi on the TRS connectors.  The editor requires a bi-directional connection to the pedal - midi-in and midi-out.  You could add a Meris MIDI I/O and use MIDI cables to connect it to the 5-pin midi ports on the MC8.

I wish I had better news for you.  Good Luck!
