### ISSUE TITLE
Cannot connect app to Enzo

### ISSUE THREAD

**Issue by mckstud2** [ElliotGarbus/Enzo-Editor-and-Librarian#8]
I'm using a USB MIDI interface connected to a Disaster Area MIDI Box One, connected to the Enzo via a TRS cable. I have set all the Enzo configurations as prescribed in the app. My PC is running Windows 10.

**Comment by ElliotGarbus** [comment]
The Disaster Area midi box is the problem. The editor requires a bidirectional connection to the pedal (midi in and midi out). The Disaster Area midi box only sends midi out. Use the Meris Midi I/O, or another bidirectional midi-box

**Comment by royvelich** [comment]
what about morningstar MC8? I couldn't get the editor to work when connecting the MC8 omni port into the enzo. I wonder if it is because it is also not a bidirectional device.

**Comment by ElliotGarbus** [comment]
@xenomarz You are correct the omni-ports on the MC-8 are not bi-directional.  The editor requires a bi-directional connection.  I expect you could connect the Meris MIDI I/O ports to the 5-pin ports on the MC-8 and connect the MC-8 to a computer via USB with the Enzo and other Meris pedals connected on the TRS ports.
