### ISSUE TITLE
Cannot connect to Enzo

### ISSUE THREAD

**Issue by SpaceCadet64** [ElliotGarbus/Enzo-Editor-and-Librarian#9]
I seem to be having an issue when connecting to my Enzo pedal.
I am on Windows 10 and am using a usb to midi adapter to connect to the Enzo via the Meris Midi I/O box.

Upon selecting the correct Midi device and channel and clicking connect I receive the message "Midi Failure: Run 'Audio Midi Setup'", with the only option being to exit, which brings up a prompt saying "Failed to execute script main". The program then closes.

The usb to midi adapter  is functional and is able to send and receive Midi data.
Not sure what else I can try here.

Any guidance would be greatly appreciated.

Thanks

**Comment by SpaceCadet64** [comment]
After reading more of the previously reported issues I have solved the problem.
Uninstalled the program, turned off antivirus and reinstalled.
Works perfectly.

Cheers.

**Comment by ElliotGarbus** [comment]
Glad to hear you got it working!
